# -*- coding: utf-8 -*-
"""Customer_Churn_Model_Decision_Comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCGqpkUhlW8KPRu2IZNFT0BCD8RCqU4v

# Comparing How ML Models Make Decisions

### Customer Churn Prediction

**Objective:** Compare how two classification models make predictions using the customer churn gold-layer dataset.

In this notebook, we will:
1. Load and inspect the customer churn dataset.
2. Prepare a gold-layer dataset.
3. Train **Logistic Regression** and **Decision Tree** models using the full dataset.
4. Inspect coefficients and tree decision rules.
5. Compare how the two models make decisions.
6. Make one sample prediction with both models.

> **Important:** This assignment focuses on understanding model behavior, not measuring accuracy. No train/test split is used.

## 1. Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

"""## 2. Upload and Load the Dataset

The uploaded file provided for this assignment is the telecom customer churn training dataset. If you are running this notebook in Google Colab, use the upload button below.

If you already have `customer_churn_gold.csv`, you can skip the gold-layer preparation section and load that file directly.
"""



import glob
import os

# Check for CSV files in the user-specified directory first
data_directory = "/content/customer_churn_dataset-training-master (1).csv"
csv_files_in_specified_dir = glob.glob(os.path.join(data_directory, "*.csv"))

if csv_files_in_specified_dir:
    raw_file = csv_files_in_specified_dir[0]
    print(f"Loading data from specified directory: {raw_file}")
else:
    # If no CSV found in the specified directory, fall back to checking the current directory
    # (e.g., for files uploaded via files.upload())
    csv_files_current_dir = glob.glob("*.csv")
    if csv_files_current_dir:
        raw_file = csv_files_current_dir[0]
        print(f"Loading data from current directory (uploaded file): {raw_file}")
    else:
        raise FileNotFoundError(
            "No CSV files found in the specified directory "
            f"('{data_directory}') or the current working directory. "
            "Please ensure the data is available."
        )

raw_df = pd.read_csv(raw_file)

print("Raw dataset loaded:", raw_file)
print("Shape:", raw_df.shape)
raw_df.head()

"""## 3. Inspect the Dataset

We check the shape, data types, and missing values before preparing the data.
"""

print("Dataset Shape:", raw_df.shape)

print("\nData Types:")
print(raw_df.dtypes)

print("\nMissing Values:")
print(raw_df.isnull().sum())

print("\nTarget Distribution:")
print(raw_df["Churn"].value_counts())

"""### Observation

The dataset contains 7,043 customer records and 21 columns. The original dataset contains no standard `NaN` values, but `TotalCharges` contains blank strings that need to be converted to numeric values. The `Churn` column is the target variable.

## 4. Prepare the Gold-Layer Dataset

The uploaded file is the original telecom churn dataset rather than an already encoded gold-layer file. Therefore, this section creates `customer_churn_gold.csv` by:

- Removing the customer ID because it does not provide useful predictive information.
- Converting `TotalCharges` to numeric values.
- Handling the few blank `TotalCharges` entries.
- Converting `Churn` from Yes/No to 1/0.
- One-hot encoding categorical features.
- Scaling numerical features for consistent model input.

This creates a fully numeric dataset that can be used directly by both models.
"""

# Make a copy for gold-layer preparation
gold_df = raw_df.copy()

# Remove customer identifier
gold_df = gold_df.drop(columns=["customerID"])

# Convert TotalCharges to numeric.
# Blank strings become NaN.
gold_df["TotalCharges"] = pd.to_numeric(
    gold_df["TotalCharges"], errors="coerce"
)

# Fill missing TotalCharges using the median
gold_df["TotalCharges"] = gold_df["TotalCharges"].fillna(
    gold_df["TotalCharges"].median()
)

# Convert target to binary
gold_df["Churn"] = gold_df["Churn"].map({"No": 0, "Yes": 1})

# Separate target before encoding
y = gold_df["Churn"]
X_raw = gold_df.drop(columns=["Churn"])

# One-hot encode categorical variables
X_encoded = pd.get_dummies(
    X_raw,
    drop_first=True,
    dtype=int
)

# Scale numerical features
numeric_features = ["SeniorCitizen", "tenure", "MonthlyCharges", "TotalCharges"]

scaler = StandardScaler()
X_encoded[numeric_features] = scaler.fit_transform(
    X_encoded[numeric_features]
)

# Final gold dataset
gold_df = X_encoded.copy()
gold_df["Churn"] = y

# Save the gold-layer dataset
gold_df.to_csv("customer_churn_gold.csv", index=False)

print("Gold dataset created and saved as customer_churn_gold.csv")
print("Gold dataset shape:", gold_df.shape)
gold_df.head()

"""## 5. Load the Gold Dataset

Now that the gold-layer dataset has been created, we load it as the dataset used for model training.
"""

df = pd.read_csv("customer_churn_gold.csv")

print("Gold dataset shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum().sum())

print("\nData types:")
print(df.dtypes.value_counts())

print("\nFirst five rows:")
display(df.head())

"""### Required Confirmation

**The customer_churn_gold.csv dataset is loaded successfully, contains 7,043 customer records with fully numeric model-ready features, and has no missing values.**

## 6. Split Features (X) and Target (y)

The target is `Churn`. All remaining columns are used as input features.
"""

X = df.drop(columns=["Churn"])
y = df["Churn"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget values:")
print(y.value_counts())

"""# Model 1: Logistic Regression

Logistic Regression uses a weighted mathematical combination of the input features. Each coefficient represents the direction and strength of a feature's contribution to the model's churn decision.

The model is trained on the **full dataset**, as required by the assignment.
"""

# Train Logistic Regression on the full dataset
log_model = LogisticRegression(max_iter=1000, random_state=42)
log_model.fit(X, y)

print("Logistic Regression trained successfully.")

print("\nIntercept:")
print(log_model.intercept_)

# Display coefficients
coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": log_model.coef_[0]
})

coef_df["Absolute_Impact"] = coef_df["Coefficient"].abs()
coef_df = coef_df.sort_values("Absolute_Impact", ascending=False)

print("\nLogistic Regression coefficients:")
display(coef_df)

"""### Logistic Regression: How It Makes Decisions

Logistic Regression uses every input feature and assigns each feature a learned coefficient. It combines the feature values and coefficients to calculate the probability that a customer will churn. The output includes a class prediction (0 = No Churn, 1 = Churn) and a probability for each class. An important observation is that the model represents the overall relationship using a linear combination of features, so positive coefficients push the prediction toward churn while negative coefficients push it away from churn.

## Inspect Logistic Regression Probabilities

The probabilities show how confident the model is about each class for individual customers.
"""

# Show predictions and probabilities for the first five customers
log_predictions = log_model.predict(X.iloc[:5])
log_probabilities = log_model.predict_proba(X.iloc[:5])

log_results = pd.DataFrame({
    "Actual_Churn": y.iloc[:5].values,
    "Prediction": log_predictions,
    "Probability_No_Churn": log_probabilities[:, 0],
    "Probability_Churn": log_probabilities[:, 1]
})

display(log_results)

"""# Model 2: Decision Tree

A Decision Tree learns a sequence of threshold-based rules. At each split, it selects a feature and threshold that separates the classes. We limit the tree depth to 3 so that its decision logic can be clearly inspected and explained.
"""

# Train Decision Tree on the full dataset
tree_model = DecisionTreeClassifier(
    max_depth=3,
    random_state=42
)

tree_model.fit(X, y)

print("Decision Tree trained successfully.")

# Print the tree's learned structure
tree = tree_model.tree_

print("Decision Tree Rules:\n")

for node_id in range(tree.node_count):
    feature_id = tree.feature[node_id]

    if feature_id != -2:
        feature_name = X.columns[feature_id]
        threshold = tree.threshold[node_id]
        print(
            f"Node {node_id}: "
            f"{feature_name} <= {threshold:.3f}"
        )
    else:
        print(f"Node {node_id}: Leaf node")

print("\nFeature importance:")
importance_df = pd.DataFrame({
    "Feature": X.columns,
    "Importance": tree_model.feature_importances_
})

importance_df = importance_df.sort_values(
    "Importance", ascending=False
)

display(importance_df[importance_df["Importance"] > 0])

# Visualize the learned decision rules
plt.figure(figsize=(20, 10))

plot_tree(
    tree_model,
    feature_names=X.columns,
    class_names=["No Churn", "Churn"],
    filled=True,
    rounded=True,
    fontsize=9
)

plt.title("Decision Tree: How the Model Makes Decisions")
plt.show()

"""### Decision Tree: How It Makes Decisions

The Decision Tree uses the available input features and creates a sequence of threshold-based questions. A customer follows one branch at each split until reaching a leaf node, where the model assigns a churn class and class probabilities. Unlike Logistic Regression, the tree does not combine all features into one equation; instead, it uses only the features needed along the customer's decision path. This makes the model highly interpretable because its prediction can be explained as a series of if-then rules.

# 7. Compare the Models on One Customer

We select one customer from the dataset and ask both models to make a prediction. This lets us see how the same input is handled by two different decision-making approaches.
"""

# Select one sample
sample_index = 0
sample = X.iloc[[sample_index]]

print("Sample customer features:")
display(sample)

# Logistic Regression prediction
log_pred = log_model.predict(sample)[0]
log_prob = log_model.predict_proba(sample)[0]

# Decision Tree prediction
tree_pred = tree_model.predict(sample)[0]
tree_prob = tree_model.predict_proba(sample)[0]

comparison = pd.DataFrame({
    "Model": ["Logistic Regression", "Decision Tree"],
    "Prediction": [log_pred, tree_pred],
    "Probability_No_Churn": [log_prob[0], tree_prob[0]],
    "Probability_Churn": [log_prob[1], tree_prob[1]]
})

display(comparison)

"""## 8. Inspect the Decision Tree Path for the Sample

The following code shows the actual rules used by the Decision Tree for the selected customer.
"""

# Find the nodes visited by the selected customer
node_indicator = tree_model.decision_path(sample)
leaf_id = tree_model.apply(sample)[0]

print("Decision path for sample customer:\n")

for node_id in node_indicator.indices:
    if node_id == leaf_id:
        print(f"Reached leaf node {node_id}.")
        continue

    feature_id = tree_model.tree_.feature[node_id]
    threshold = tree_model.tree_.threshold[node_id]
    feature_name = X.columns[feature_id]
    feature_value = sample.iloc[0, feature_id]

    if feature_value <= threshold:
        direction = "<="
    else:
        direction = ">"

    print(
        f"Node {node_id}: "
        f"{feature_name} = {feature_value:.3f} "
        f"{direction} {threshold:.3f}"
    )

"""### Sample Prediction Comparison

For the selected customer, Logistic Regression considers the contribution of all available features at the same time and converts their combined effect into a churn probability. The Decision Tree instead follows a small number of threshold-based rules and reaches a leaf node. Therefore, even when both models receive exactly the same customer information, they can explain their decisions differently: Logistic Regression gives a weighted overall calculation, while the Decision Tree gives a sequence of if-then decisions.

# 9. Model Comparison

Logistic Regression and Decision Tree models represent relationships between customer features and churn in very different ways. Logistic Regression uses a linear combination of all input features, with each feature receiving a coefficient that indicates whether it pushes the prediction toward or away from churn. The Decision Tree instead learns a set of threshold-based rules and divides customers into branches according to their feature values. Both models are interpretable, but their explanations are different: Logistic Regression can be understood through its coefficients, while a Decision Tree can be followed as a sequence of if-then rules. Logistic Regression therefore learns an overall linear pattern, whereas the Decision Tree can capture threshold-based and more complex relationships. One interesting observation is that the Decision Tree may ignore many features for a particular prediction if they are not needed along that customer's path. Logistic Regression, in contrast, considers all available features when calculating the final probability. This shows that different models can “think” about the same customer in fundamentally different ways.

# 10. What I Learned

- **Logistic Regression:** thinks in terms of weighted feature contributions and probabilities.
- **Decision Tree:** thinks in terms of sequential rules and thresholds.
- **Logistic Regression:** gives a global view of how features influence the prediction.
- **Decision Tree:** gives a direct path explaining an individual prediction.
- Model behavior can be very different even when both models use the same dataset.
- This assignment focuses on understanding decision-making rather than comparing accuracy.

# Conclusion

This exercise demonstrated how two classification algorithms can approach the same customer churn problem differently. Logistic Regression produces predictions from a weighted combination of features, while the Decision Tree builds a sequence of decision rules. Inspecting coefficients, probabilities, tree splits, feature importance, and a sample decision path made the internal logic of both models easier to understand. No performance comparison was performed because the purpose of this assignment was to understand how the models make decisions.

## Module 8: Deploying a Customer Churn Model

This section will focus on deploying the previously trained customer churn model. The main objectives are:
1.  **Host the model as an HTTP API:** This will allow the model to be reused in other projects for real-time predictions.
2.  **Run a nightly batch job:** Score all active customers overnight and store the predictions.
3.  **Track performance:** Implement basic monitoring metrics.
4.  **Propose a maintenance plan:** Ensure the model remains reliable.

### 1. Host the model as an HTTP API

We will use `FastAPI` to create a real-time inference API. First, let's install the necessary libraries.
"""

import sys

# Install FastAPI and Uvicorn
!{sys.executable} -m pip install fastapi uvicorn pydantic scikit-learn

"""Next, we'll save our trained `Logistic Regression` model and the `StandardScaler` to disk so they can be loaded by the API. We'll use `joblib` for this."""

import joblib

# Save the Logistic Regression model
joblib.dump(log_model, 'logistic_regression_model.joblib')
print("Logistic Regression model saved as 'logistic_regression_model.joblib'")

# To save the scaler, we need access to the original scaler used for X_encoded[numeric_features]
# Let's re-run the scaling step to get the scaler object if it's not already globally available.
# Assuming 'scaler' is still in scope from cell 2d5db723, otherwise we would need to re-initialize and fit.

# Re-initialize and fit scaler on numeric features from the raw_df if not already available
# This block ensures we have the correct scaler object if the notebook was run out of order.
from sklearn.preprocessing import StandardScaler

# Load raw_df again to ensure consistency for scaler fitting
raw_df = pd.read_csv(raw_file) # raw_file was defined earlier

# Make a copy for gold-layer preparation (similar to cell 2d5db723)
gold_df_temp = raw_df.copy()

# Convert TotalCharges to numeric. Blank strings become NaN.
gold_df_temp["TotalCharges"] = pd.to_numeric(gold_df_temp["TotalCharges"], errors="coerce")

# Fill missing TotalCharges using the median
gold_df_temp["TotalCharges"] = gold_df_temp["TotalCharges"].fillna(
gold_df_temp["TotalCharges"].median())

# Numeric features for scaling
numeric_features = ["SeniorCitizen", "tenure", "MonthlyCharges", "TotalCharges"]

# Fit scaler only on the numeric data that would be fed to the model
scaler_for_api = StandardScaler()
scaler_for_api.fit(gold_df_temp[numeric_features])

# Save the scaler
joblib.dump(scaler_for_api, 'scaler.joblib')
print("Scaler saved as 'scaler.joblib'")